[tool.poetry]
name = "celestiumauth"
version = "0.1.0"
description = ""
authors = ["meguowo-lab <file.name.infected@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
